### ISSUE TITLE
About experiments on house-price

### ISSUE THREAD

**Issue by guosyjlu** [snap-stanford/MLAgentBench#6]
Hi, thanks for your great work! I am wondering how to evaluate the "success" for house-price task, given that there is not a baseline code. Is the improvement of 10% evaluated based on the sample submission csv file? Looking forward to your reply.

**Comment by q-hwang** [comment]
We used 1e10 as a baseline number since the starter code does not produce anything.

**Comment by guosyjlu** [comment]
So for benchmarks whose starter codes are incomplete, the success means that the agent can successfully fill in the code and execute. Right?

**Comment by q-hwang** [comment]
Yeah basically

**Comment by guosyjlu** [comment]
Thanks for your reply.
