### ISSUE TITLE
How to run the docker image?

### ISSUE THREAD

**Issue by KevinH48264** [snap-stanford/MLAgentBench#7]
Really great work and I'd love to play around with this!

FYI, I'm on a Windows computer and tried to set up the code locally and just ran into many errors of packages not working for Windows. While I tried to re-install and edit the code, I think the best option for Windows users is likely to use the docker image as suggested in the README file -- if it works, which I believe it should?

I've used docker before, but **I was wondering if you would be able to include information about how you intended to have the docker image be used and ran to benchmark against a Kaggle dataset?** 

I pulled the image, but what are the recommended next steps? I tried running in interactive mode, but I couldn't actually see the MLAgentBench folder for some reason so I'm not sure if I'm missing something.

**Comment by q-hwang** [comment]
The docker image only has all the dependencies installed but does not have the code or running command baked in. You would still need to clone the repo and follow the running commands in README. Hope it helps!

**Comment by KevinH48264** [comment]
I'll give it a try, thank you!
